Vid-ly/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Vid_ly.Models;

namespace Vid_ly.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _configuration;

        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _logger = logger;
            this._configuration = configuration;
        }

        public IActionResult Index()
        {
            var msg = _configuration["ConnectionStrings:DefaultConnection"];
            return View("Index",msg);
        }
               
        [HttpGet("videos/{id:int}")]
        public IActionResult Video(int Id)
        {
            return View();
        }

        [HttpGet("channels")]
        public IActionResult Channel()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Vid-ly/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Vid_ly.Controllers
{
    public class VideoController : Controller
    {
        public IActionResult Index(int Id)
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create(int Id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Update(int Id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Delete(int Id)
        {
            return View();
        }        

    }
}

Vid-ly/Views/Home/Index.cshtml
@{
   ViewData["Title"] = "Now Trending";
}

<section class="container">
    <div class="d-flex justify-content-between main-header mb-3">
        <h6>@ViewData["Title"]</h6>
        <p>Sort by <i class="fas fa-arrow-circle-down"></i></p>
    </div>

<div class="d-flex justify-content-around flex-wrap">
    <div class="card box box-shadow">
        <a asp-controller="Video" asp-action="Index" asp-route-Id="343">
            <img class="card-img-top" src="~/img/286px180.png" alt="Card image cap">
            <div class="card-body bg-light m-0 p-0 pt-2 d-flex">
                <div>
                    <img class="user-icon-video rounded-circle" alt="" src="~/img/s1.png">
                </div>
                <div class="pl-1 pt-0">
                    <h5 class="card-title">There are many variations of passages of Lorem today and tomorrow</h5>
                    <p class="card-text text-success">Education</p>
                </div>
            </div>
            <div class="d-flex justify-content-between align-content-center view-days p-2">
                <div>18M views</div>
                <div>2 days ago</div>
            </div>
        </a>
    </div>
    <div class="card box box-shadow">
        <a asp-controller="Video" asp-action="Index" asp-route-Id="343">
            <img class="card-img-top" src="~/img/286px180.png" alt="Card image cap">
            <div class="card-body bg-light m-0 p-0 pt-2 d-flex">
                <div>
                    <img class="user-icon-video rounded-circle" alt="" src="~/img/s1.png">
                </div>
                <div class="pl-1 pt-0">
                    <h5 class="card-title">There are many variations of passages of Lorem today and tomorrow</h5>
                    <p class="card-text text-success">Education</p>
                </div>
            </div>
            <div class="d-flex justify-content-between align-content-center view-days p-2">
                <div>18M views</div>
                <div>2 days ago</div>
            </div>
        </a>
    </div>
    <div class="card box box-shadow">
        <a asp-controller="Video" asp-action="Index" asp-route-Id="343">
            <img class="card-img-top" src="~/img/286px180.png" alt="Card image cap">
            <div class="card-body bg-light m-0 p-0 pt-2 d-flex">
                <div>
                    <img class="user-icon-video rounded-circle" alt="" src="~/img/s1.png">
                </div>
                <div class="pl-1 pt-0">
                    <h5 class="card-title">There are many variations of passages of Lorem today and tomorrow</h5>
                    <p class="card-text text-success">Education</p>
                </div>
            </div>
            <div class="d-flex justify-content-between align-content-center view-days p-2">
                <div>18M views</div>
                <div>2 days ago</div>
            </div>
        </a>
    </div>
    <div class="card box box-shadow">
        <a asp-controller="Video" asp-action="Index" asp-route-Id="343">
            <img class="card-img-top" src="~/img/286px180.png" alt="Card image cap">
            <div class="card-body bg-light m-0 p-0 pt-2 d-flex">
                <div>
                    <img class="user-icon-video rounded-circle" alt="" src="~/img/s1.png">
                </div>
                <div class="pl-1 pt-0">
                    <h5 class="card-title">There are many variations of passages of Lorem today and tomorrow</h5>
                    <p class="card-text text-success">Education</p>
                </div>
            </div>
            <div class="d-flex justify-content-between align-content-center view-days p-2">
                <div>18M views</div>
                <div>2 days ago</div>
            </div>
        </a>
    </div>
    <div class="card box box-shadow">
        <a asp-controller="Video" asp-action="Index" asp-route-Id="343">
            <img class="card-img-top" src="~/img/286px180.png" alt="Card image cap">
            <div class="card-body bg-light m-0 p-0 pt-2 d-flex">
                <div>
                    <img class="user-icon-video rounded-circle" alt="" src="~/img/s1.png">
                </div>
                <div class="pl-1 pt-0">
                    <h5 class="card-title">There are many variations of passages of Lorem today and tomorrow</h5>
                    <p class="card-text text-success">Education</p>
                </div>
            </div>
            <div class="d-flex justify-content-between align-content-center view-days p-2">
                <div>18M views</div>
                <div>2 days ago</div>
            </div>
        </a>
    </div>

    <div class="card box box-shadow">
        <a asp-controller="Video" asp-action="Index" asp-route-Id="343">
            <img class="card-img-top" src="~/img/286px180.png" alt="Card image cap">
            <div class="card-body bg-light m-0 p-0 pt-2 d-flex">
                <div>
                    <img class="user-icon-video rounded-circle" alt="" src="~/img/s1.png">
                </div>
                <div class="pl-1 pt-0">
                    <h5 class="card-title">There are many variations of passages of Lorem today and tomorrow</h5>
                    <p class="card-text text-success">Education</p>
                </div>
            </div>
            <div class="d-flex justify-content-between align-content-center view-days p-2">
                <div>18M views</div>
                <div>2 days ago</div>
            </div>
        </a>
    </div>
    <div class="card box box-shadow">
        <a asp-controller="Video" asp-action="Index" asp-route-Id="343">
            <img class="card-img-top" src="~/img/286px180.png" alt="Card image cap">
            <div class="card-body bg-light m-0 p-0 pt-2 d-flex">
                <div>
                    <img class="user-icon-video rounded-circle" alt="" src="~/img/s1.png">
                </div>
                <div class="pl-1 pt-0">
                    <h5 class="card-title">There are many variations of passages of Lorem today and tomorrow</h5>
                    <p class="card-text text-success">Education</p>
                </div>
            </div>
            <div class="d-flex justify-content-between align-content-center view-days p-2">
                <div>18M views</div>
                <div>2 days ago</div>
            </div>
        </a>
    </div>
    <div class="card box box-shadow">
        <a asp-controller="Video" asp-action="Index" asp-route-Id="343">
            <img class="card-img-top" src="~/img/286px180.png" alt="Card image cap">
            <div class="card-body bg-light m-0 p-0 pt-2 d-flex">
                <div>
                    <img class="user-icon-video rounded-circle" alt="" src="~/img/s1.png">
                </div>
                <div class="pl-1 pt-0">
                    <h5 class="card-title">There are many variations of passages of Lorem today and tomorrow</h5>
                    <p class="card-text text-success">Education</p>
                </div>
            </div>
            <div class="d-flex justify-content-between align-content-center view-days p-2">
                <div>18M views</div>
                <div>2 days ago</div>
            </div>
        </a>
    </div>
</div>

<div class="my-4">
    <nav class="d-flex flex-row justify-content-center align-items-center">
        <a class="mr-2 px-3 py-2 grey pageNumber" href="#">Previous</a>
        <a class="mr-2 px-3 py-2 active pageNumber" href="#">1</a>
        <a class="mr-2 px-3 py-2 pageNumber" href="#">2</a>
        <a class="mr-2 px-3 py-2 pageNumber" href="#">3</a>
        <a class="mr-2 px-3 py-2 pageNumber" href="#">Next</a>
    </nav>
</div>

</section>