Vid-ly/Controllers/ChannelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Vid_ly.Controllers
{
    public class ChannelController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("channel/{id:int}")]
        public IActionResult Channel(int Id)
        {
            return View(Id);
        }

        [HttpGet]
        public IActionResult Create(int Id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Update(int Id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Delete(int Id)
        {
            return View();
        }

    }
}

Vid-ly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vid-ly | @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/all.min.css" rel="stylesheet" />
    @RenderSection("styles", false);
</head>
<body>
    <header class="p-1">
        <nav class="mb-2 d-flex flex-row justify-content-around align-items-center">
            &nbsp;&nbsp;
            <button class="btn btn-link btn-sm text-secondary" id="sidebarToggle">
                <i class="fas fa-bars"></i>
            </button> &nbsp;&nbsp;
            <a class="navbar-brand text-left" asp-area="" asp-controller="Home" asp-action="Index">Vid-ly</a>
            <!-- Navbar Search -->
            <form class="d-none d-md-inline-block form-inline ml-auto flex-grow-1 form-search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <div class="input-group-append">
                        <button class="btn btn-light" type="button">
                            <i class="input-group-append-icon fas fa-search px-1"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Navbar -->
            <ul class="navbar-nav ml-auto d-flex flex-row align-items-center">
                <li class="nav-item mx-3">
                    <a class="nav-link" asp-controller="Account" asp-action="Upload">
                        <i class="fas fa-plus-circle fa-fw"></i>
                        Upload Video
                    </a>
                </li>
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle user-dropdown-link" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img class="img-icon" alt="" src="~/img/s1.png">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" asp-controller="Account" asp-action="Index"><i class="fas fa-fw fa-user-circle"></i> &nbsp; My Account</a>
                        <a class="dropdown-item" href="subscriptions.html"><i class="fas fa-fw fa-video"></i> &nbsp; Subscriptions</a>
                        <a class="dropdown-item" asp-controller="Account" asp-action="Index"><i class="fas fa-fw fa-cog"></i> &nbsp; Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal"><i class="fas fa-fw fa-sign-out-alt"></i> &nbsp; Logout</a>
                    </div>
                </li>
            </ul>
        </nav>
    </header>
    <aside class="left-panel pb-5">
        <ul class="list-group list-group-flush aside-list-group">
            <a asp-controller="Home" asp-action="index">
                <li class="list-group-item list-group-item-action">
                    <i class="mr-3 fas fa-home"></i>Home
                </li>
            </a>
            <a asp-controller="Home" asp-action="index">
                <li class="list-group-item list-group-item-action">
                    <i class="mr-3 fas fa-fire"></i>Trending
                </li>
            </a>
            <a asp-controller="Channel" asp-action="Index">
                <li class="list-group-item list-group-item-action">
                    <span><i class="mr-3 fas fa-users"></i></span>Channels
                </li>
            </a>
            <a asp-controller="Home" asp-action="index">
                <li class="list-group-item list-group-item-action">
                    <i class="mr-3 fas fa-thumbs-up"></i>Liked Videos
                </li>
            </a>
            <a asp-controller="Home" asp-action="index">
                <li class="list-group-item list-group-item-action">
                    <i class="mr-3 fas fa-history"></i>History Page
                </li>
            </a>
        </ul>
        <hr />
        <ul class="list-group list-group-flush aside-list-group mb-2">
            <a asp-controller="Channel" asp-action="Channel" asp-route-Id="343">
                <li class="list-group-item list-group-item-action">
                    <i class="mr-3 fas fa-user-circle"></i>Your Channel
                </li>
            </a>
        </ul>
        <hr />
        <h6 class="m-3 mr-5">SUBSCRIPTIONS</h6>
        <ul class="list-group list-group-flush aside-list-group mb-2">
            <li class="list-group-item list-group-item-action d-flex align-items-center">
                <img class="img-icon mr-3" alt="" src="~/img/s1.png">CodingWithStephen
            </li>
            <li class="list-group-item list-group-item-action d-flex align-items-center">
                <img class="img-icon mr-3" alt="" src="~/img/s1.png">Net Naija
            </li>
            <li class="list-group-item list-group-item-action d-flex align-items-center">
                <img class="img-icon mr-3" alt="" src="~/img/s1.png">Code Evolution
            </li>
            <li class="list-group-item list-group-item-action d-flex align-items-center">
                <img class="img-icon mr-3" alt="" src="~/img/s1.png">FreeCodeCamp
            </li>
            <li class="list-group-item list-group-item-action d-flex align-items-center">
                <img class="img-icon mr-3" alt="" src="~/img/s1.png">Now Coding
            </li>
            <li class="list-group-item list-group-item-action d-flex align-items-center">
                <img class="img-icon mr-3" alt="" src="~/img/s1.png">Google Developers
            </li>
            <li class="list-group-item list-group-item-action d-flex align-items-center">
                <img class="img-icon mr-3" alt="" src="~/img/s1.png">Microsoft Developer
            </li>
        </ul>
        <hr />
        <ul class="list-group list-group-flush aside-list-group mb-5">
            <a asp-controller="Account" asp-action="Index">
                <li class="list-group-item list-group-item-action">
                    <i class="mr-3 fas fa-cog"></i>Setting
                </li>
            </a>
            <li class="list-group-item list-group-item-action">
                <i class="mr-3 fas fa-comment-alt"></i>Send feedback
            </li>
        </ul>
    </aside>

    <main role="main">
        @RenderBody()
        <div class="footer mt-4 p-4 grey d-flex flex-row justify-content-between">
            <p>© Copyright 2020. All Rights Reserved</p>
            <div>
                <span>Made with <i class="fas fa-heart"></i> <span class="developer">by Ohien Stephen</span></span>
            </div>
        </div>
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>